include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Allow using BuildContext across async gaps in simple cases
    use_build_context_synchronously: false
    # Allow dangling library doc comments
    dangling_library_doc_comments: false

analyzer:
  errors:
    todo: ignore
    deprecated_member_use_from_same_package: ignore
    deprecated_member_use: warning
